# Generated by Django 5.1.1 on 2024-12-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersApp', '0003_alter_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_delivery_address',
            field=models.TextField(null=True),
        ),
    ]
