# Generated by Django 5.1.2 on 2025-05-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersApp', '0004_order_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_proof',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(blank=True, choices=[('To Be Refunded', 'To Be Refunded'), ('Refunded', 'Refunded')], max_length=20, null=True),
        ),
    ]
