# Generated by Django 5.1.1 on 2025-01-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0002_product_onsale_product_saleprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subCategory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
